// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXzAkBGbhRuppzcZTteiE1QS6iIUHXjFQ',
    appId: '1:653290580720:web:a675fa963cb7efaf077035',
    messagingSenderId: '653290580720',
    projectId: 'exam-system-d7709',
    authDomain: 'exam-system-d7709.firebaseapp.com',
    storageBucket: 'exam-system-d7709.firebasestorage.app',
    measurementId: 'G-WFBT2L3LG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByM-iIw4J2WxNRxiKMB2Iu7SlRVG-k4Xc',
    appId: '1:653290580720:android:bf34222e8c702155077035',
    messagingSenderId: '653290580720',
    projectId: 'exam-system-d7709',
    storageBucket: 'exam-system-d7709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0w6y5QF8g9IJMv0B-j01c6lFpSDhklpg',
    appId: '1:653290580720:ios:bb0a45f743a3dcc8077035',
    messagingSenderId: '653290580720',
    projectId: 'exam-system-d7709',
    storageBucket: 'exam-system-d7709.firebasestorage.app',
    iosBundleId: 'com.example.newStudentDashBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0w6y5QF8g9IJMv0B-j01c6lFpSDhklpg',
    appId: '1:653290580720:ios:bb0a45f743a3dcc8077035',
    messagingSenderId: '653290580720',
    projectId: 'exam-system-d7709',
    storageBucket: 'exam-system-d7709.firebasestorage.app',
    iosBundleId: 'com.example.newStudentDashBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXzAkBGbhRuppzcZTteiE1QS6iIUHXjFQ',
    appId: '1:653290580720:web:f6a06cbccaf05564077035',
    messagingSenderId: '653290580720',
    projectId: 'exam-system-d7709',
    authDomain: 'exam-system-d7709.firebaseapp.com',
    storageBucket: 'exam-system-d7709.firebasestorage.app',
    measurementId: 'G-WX9FBY1WLW',
  );
}
